# Generated by Django 5.1.3 on 2024-11-11 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoriamodel',
            table='categorias',
        ),
    ]
