# Generated by Django 5.1.3 on 2024-11-11 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0002_alter_categoriamodel_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamodel',
            name='imagen',
            field=models.ImageField(height_field=50, null=True, upload_to='imagen', width_field=50),
        ),
    ]
