# Generated by Django 5.1.3 on 2024-11-11 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0003_alter_categoriamodel_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriamodel',
            name='imagen',
            field=models.ImageField(null=True, upload_to='imagen'),
        ),
    ]
