# Generated by Django 5.1.2 on 2024-10-21 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='categoriasmodel',
            table='categorias',
        ),
    ]
