# Generated by Django 5.1.2 on 2024-10-27 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('stock', models.IntegerField()),
                ('visibilidad', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'productos',
            },
        ),
    ]
